#!/usr/bin/env bash
# Prepare a bare Ubuntu 24.04 host to run dora-loop.
#
# In the repository rather than typed at a shell, because a deploy target
# configured by remembered commands is a target nobody can rebuild. Run it more
# than once safely: every step checks before it acts and says which it took, so
# the output is a description of the machine rather than of this run.
#
# It deliberately does NOT install the application, write the ingest token, or
# start anything. Provisioning makes a machine capable of running the service;
# deploying decides which build runs. Keeping those apart is what makes rollback
# possible -- a rollback re-points a symlink, it does not re-provision a host.
#
#   sudo ./provision-vm.sh
#
set -euo pipefail

APP_USER=dora            # runs the service; owns nothing it does not need
DEPLOY_USER=deploy       # ships releases; the only account CI authenticates as
APP_DIR=/opt/dora-loop
ETC_DIR=/etc/dora-loop
DB_NAME=doraloop
DB_USER=doraloop

[ "$(id -u)" -eq 0 ] || { echo "must run as root" >&2; exit 1; }

step() { printf '\n== %s\n' "$1"; }
did()  { printf '   %s\n' "$1"; }

step "packages"
if ! command -v java >/dev/null 2>&1 || ! command -v psql >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    # JRE, not JDK: this host runs a jar, it does not compile one. A compiler on
    # a deploy target is reach an attacker does not need to be given.
    apt-get install -y -qq openjdk-21-jre-headless postgresql postgresql-client >/dev/null
    did "installed openjdk-21-jre-headless and postgresql"
else
    did "already present: $(java -version 2>&1 | head -1)"
fi

step "service account"
if ! id "$APP_USER" >/dev/null 2>&1; then
    # No login shell and no home: this account exists to own a process, and
    # anything that can become it should get as little as possible.
    useradd --system --no-create-home --shell /usr/sbin/nologin "$APP_USER"
    did "created system user $APP_USER"
else
    did "system user $APP_USER exists"
fi

step "deploy account"
if ! id "$DEPLOY_USER" >/dev/null 2>&1; then
    useradd --create-home --shell /bin/bash "$DEPLOY_USER"
    did "created $DEPLOY_USER"
else
    did "$DEPLOY_USER exists"
fi

# CI authenticates as this account, so what it is allowed to do is the blast
# radius of a compromised pipeline. It gets three systemctl verbs against one
# unit and nothing else -- not `systemctl *`, which would include `edit` and
# therefore arbitrary root execution.
cat > /etc/sudoers.d/dora-loop <<SUDOERS
$DEPLOY_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart dora-loop, /usr/bin/systemctl stop dora-loop, /usr/bin/systemctl start dora-loop, /usr/bin/systemctl is-active dora-loop, /usr/bin/systemctl show dora-loop *
SUDOERS
chmod 0440 /etc/sudoers.d/dora-loop
visudo -cf /etc/sudoers.d/dora-loop >/dev/null
did "sudoers: three systemctl verbs on dora-loop, nothing else"

step "directories"
# Releases are kept side by side and a symlink chooses one. Rollback is then a
# symlink flip and a restart, prepared before the change rather than improvised
# after it -- which is the only kind of rollback that works during an incident.
install -d -o "$DEPLOY_USER" -g "$APP_USER" -m 0750 "$APP_DIR" "$APP_DIR/releases"
install -d -o root -g "$APP_USER" -m 0750 "$ETC_DIR"
did "$APP_DIR (releases/, current -> a release) and $ETC_DIR"

step "database"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
    # Generated here and never transmitted. The application and the database
    # share a host and speak over loopback, so this password does not need to
    # exist anywhere else -- and a secret that exists in one place cannot drift
    # between two. CI never learns it.
    DB_PASS="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
    sudo -u postgres psql -qc "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS'" >/dev/null
    sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
    umask 027
    cat > "$ETC_DIR/db.env" <<DBENV
# Generated by provision-vm.sh. Not written by deploys, so a deploy cannot
# clobber it and a rotation here does not require a release.
SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/$DB_NAME
SPRING_DATASOURCE_USERNAME=$DB_USER
SPRING_DATASOURCE_PASSWORD=$DB_PASS
DBENV
    chown root:"$APP_USER" "$ETC_DIR/db.env"
    chmod 0640 "$ETC_DIR/db.env"
    unset DB_PASS
    did "created role $DB_USER, database $DB_NAME, and $ETC_DIR/db.env"
else
    did "role $DB_USER already exists; leaving it and db.env alone"
fi

# Loopback only. The filter in the application cannot see the database, so
# anything that can reach Postgres with these credentials can write deployment
# events directly, bypassing the idempotency digest and every other control.
PG_CONF=$(sudo -u postgres psql -tAc 'SHOW config_file')
if ! grep -qE "^listen_addresses = '127.0.0.1'" "$PG_CONF"; then
    sed -i "s/^#*listen_addresses.*/listen_addresses = '127.0.0.1'/" "$PG_CONF"
    systemctl restart postgresql
    did "postgres bound to 127.0.0.1 only"
else
    did "postgres already bound to 127.0.0.1"
fi

step "app environment placeholder"
# Written by the deploy job on every release (token, build sha). Created empty
# here so the unit can reference it before a first deploy has happened --
# systemd fails a unit whose EnvironmentFile is missing, and "the service will
# not start on a fresh host" is a bad thing to discover during a deploy.
#
# Empty is safe: with no DORA_INGEST_TOKEN the service refuses writes with 503
# rather than accepting them unauthenticated.
if [ ! -f "$ETC_DIR/app.env" ]; then
    install -o "$DEPLOY_USER" -g "$APP_USER" -m 0640 /dev/null "$ETC_DIR/app.env"
    did "created empty $ETC_DIR/app.env (writable by $DEPLOY_USER)"
else
    did "$ETC_DIR/app.env exists"
fi

step "systemd unit"
install -o root -g root -m 0644 "$(dirname "$0")/dora-loop.service" \
    /etc/systemd/system/dora-loop.service
systemctl daemon-reload
systemctl enable dora-loop >/dev/null 2>&1 || true
did "installed and enabled dora-loop.service (not started: nothing is deployed)"

step "done"
did "provisioned. Deploy a release, then: systemctl start dora-loop"
